// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/meoconbatu/cmsgrpc/user/proto-files/user-service.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticateUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserRequest) Reset()         { *m = AuthenticateUserRequest{} }
func (m *AuthenticateUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserRequest) ProtoMessage()    {}
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae4b6464daf1a137, []int{0}
}

func (m *AuthenticateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserRequest.Unmarshal(m, b)
}
func (m *AuthenticateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserRequest.Merge(m, src)
}
func (m *AuthenticateUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserRequest.Size(m)
}
func (m *AuthenticateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserRequest proto.InternalMessageInfo

func (m *AuthenticateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AuthenticateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateUserResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserResponse) Reset()         { *m = AuthenticateUserResponse{} }
func (m *AuthenticateUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserResponse) ProtoMessage()    {}
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae4b6464daf1a137, []int{1}
}

func (m *AuthenticateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserResponse.Unmarshal(m, b)
}
func (m *AuthenticateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserResponse.Merge(m, src)
}
func (m *AuthenticateUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserResponse.Size(m)
}
func (m *AuthenticateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserResponse proto.InternalMessageInfo

func (m *AuthenticateUserResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type NewUserResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserResponse) Reset()         { *m = NewUserResponse{} }
func (m *NewUserResponse) String() string { return proto.CompactTextString(m) }
func (*NewUserResponse) ProtoMessage()    {}
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae4b6464daf1a137, []int{2}
}

func (m *NewUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserResponse.Unmarshal(m, b)
}
func (m *NewUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserResponse.Marshal(b, m, deterministic)
}
func (m *NewUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserResponse.Merge(m, src)
}
func (m *NewUserResponse) XXX_Size() int {
	return xxx_messageInfo_NewUserResponse.Size(m)
}
func (m *NewUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserResponse proto.InternalMessageInfo

func (m *NewUserResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae4b6464daf1a137, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticateUserRequest)(nil), "user.AuthenticateUserRequest")
	proto.RegisterType((*AuthenticateUserResponse)(nil), "user.AuthenticateUserResponse")
	proto.RegisterType((*NewUserResponse)(nil), "user.NewUserResponse")
	proto.RegisterType((*Error)(nil), "user.Error")
}

func init() {
	proto.RegisterFile("github.com/meoconbatu/cmsgrpc/user/proto-files/user-service.proto", fileDescriptor_ae4b6464daf1a137)
}

var fileDescriptor_ae4b6464daf1a137 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xa5, 0xd2, 0x5a, 0x9d, 0x1c, 0x94, 0x05, 0x31, 0x04, 0x14, 0x0d, 0x1e, 0x3c, 0xd8, 0x04,
	0xaa, 0x1e, 0x3c, 0x78, 0xa8, 0xe0, 0xb5, 0xd0, 0x88, 0x17, 0x6f, 0x9b, 0xed, 0x98, 0x06, 0xdc,
	0x6c, 0xdc, 0xd9, 0xb5, 0x7f, 0xe1, 0x37, 0xcb, 0xee, 0x26, 0x1e, 0x2a, 0x45, 0xf4, 0x36, 0xef,
	0xbd, 0xdd, 0x37, 0x6f, 0x66, 0x60, 0x56, 0xd5, 0x66, 0x65, 0xcb, 0x4c, 0x28, 0x99, 0x4b, 0x54,
	0x42, 0x35, 0x25, 0x37, 0x36, 0x17, 0x92, 0x2a, 0xdd, 0x8a, 0xdc, 0x12, 0xea, 0xbc, 0xd5, 0xca,
	0xa8, 0xc9, 0x6b, 0xfd, 0x86, 0xe4, 0x89, 0x09, 0xa1, 0xfe, 0xa8, 0x05, 0x66, 0x5e, 0x60, 0x43,
	0xc7, 0x25, 0x77, 0xff, 0x30, 0x0a, 0x06, 0xe9, 0x02, 0x8e, 0x67, 0xd6, 0xac, 0xb0, 0x31, 0xb5,
	0xe0, 0x06, 0x9f, 0x09, 0x75, 0x81, 0xef, 0x16, 0xc9, 0xb0, 0x04, 0xf6, 0xdc, 0xc3, 0x39, 0x97,
	0x18, 0x0f, 0xce, 0x06, 0x97, 0xfb, 0xc5, 0x37, 0x76, 0x5a, 0xcb, 0x89, 0xd6, 0x4a, 0x2f, 0xe3,
	0x9d, 0xa0, 0xf5, 0x38, 0xbd, 0x87, 0xf8, 0xa7, 0x25, 0xb5, 0xaa, 0x21, 0x64, 0xe7, 0x30, 0x42,
	0xad, 0x95, 0xf6, 0x86, 0xd1, 0x34, 0xca, 0x7c, 0x94, 0x47, 0x47, 0x15, 0x41, 0x49, 0x6f, 0xe0,
	0x60, 0x8e, 0xeb, 0xbf, 0xfe, 0xba, 0x85, 0x91, 0xc7, 0x8c, 0xc1, 0x50, 0xa8, 0x65, 0x9f, 0xd8,
	0xd7, 0x2c, 0x86, 0xb1, 0x44, 0x22, 0x5e, 0x61, 0x17, 0xb6, 0x87, 0xd3, 0xcf, 0x01, 0x44, 0xae,
	0xd5, 0x53, 0xd8, 0x2a, 0x5b, 0xc0, 0xe1, 0x66, 0x76, 0x76, 0x12, 0xda, 0x6d, 0x59, 0x53, 0x72,
	0xba, 0x4d, 0xee, 0xc2, 0x5f, 0xc1, 0xb8, 0x9b, 0x87, 0x41, 0x78, 0xea, 0xea, 0xe4, 0x28, 0xd4,
	0x1b, 0xa3, 0x3e, 0x5c, 0xbc, 0xa4, 0xbf, 0x1f, 0xb3, 0xdc, 0xf5, 0xc7, 0xbb, 0xfe, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0xdf, 0x3a, 0xb7, 0x42, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error)
	NewUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*NewUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error) {
	out := new(AuthenticateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/AuthenticateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) NewUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*NewUserResponse, error) {
	out := new(NewUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/NewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error)
	NewUser(context.Context, *User) (*NewUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) AuthenticateUser(ctx context.Context, req *AuthenticateUserRequest) (*AuthenticateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (*UnimplementedUserServiceServer) NewUser(ctx context.Context, req *User) (*NewUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/AuthenticateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AuthenticateUser(ctx, req.(*AuthenticateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/NewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).NewUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateUser",
			Handler:    _UserService_AuthenticateUser_Handler,
		},
		{
			MethodName: "NewUser",
			Handler:    _UserService_NewUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/meoconbatu/cmsgrpc/user/proto-files/user-service.proto",
}
