// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/meoconbatu/cmsgrpc/view/proto-files/repository.proto

package view

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Page struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6596f5594b287a9, []int{0}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Page) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Page) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Page)(nil), "domain.Page")
}

func init() {
	proto.RegisterFile("github.com/meoconbatu/cmsgrpc/view/proto-files/repository.proto", fileDescriptor_e6596f5594b287a9)
}

var fileDescriptor_e6596f5594b287a9 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4d, 0xcd, 0x4f, 0xce, 0xcf, 0x4b, 0x4a, 0x2c,
	0x29, 0xd5, 0x4f, 0xce, 0x2d, 0x4e, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0xcb, 0x4c, 0x2d, 0xd7, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4d, 0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0x2f, 0x4a, 0x2d, 0xc8, 0x2f,
	0xce, 0x2c, 0xc9, 0x2f, 0xaa, 0xd4, 0x03, 0x0b, 0x0b, 0xb1, 0xa5, 0xe4, 0xe7, 0x26, 0x66, 0xe6,
	0x29, 0xb9, 0x71, 0xb1, 0x04, 0x24, 0xa6, 0xa7, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x30, 0x07, 0x31, 0x65, 0xa6, 0x08, 0x89, 0x70, 0xb1, 0x96, 0x64, 0x96, 0xe4,
	0xa4, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x12, 0x5c, 0xec, 0xc9, 0xf9,
	0x79, 0x25, 0xa9, 0x79, 0x25, 0x12, 0xcc, 0x60, 0x71, 0x18, 0xd7, 0x49, 0x25, 0x4a, 0x89, 0xb0,
	0x93, 0x92, 0xd8, 0xc0, 0x96, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71, 0x42, 0x2e, 0x4b,
	0xbf, 0x00, 0x00, 0x00,
}
