// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/meoconbatu/cmsgrpc/view/proto-files/user-service.proto

package view

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticateUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserRequest) Reset()         { *m = AuthenticateUserRequest{} }
func (m *AuthenticateUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserRequest) ProtoMessage()    {}
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef360b9da723b7a0, []int{0}
}

func (m *AuthenticateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserRequest.Unmarshal(m, b)
}
func (m *AuthenticateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserRequest.Merge(m, src)
}
func (m *AuthenticateUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserRequest.Size(m)
}
func (m *AuthenticateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserRequest proto.InternalMessageInfo

func (m *AuthenticateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AuthenticateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateUserResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserResponse) Reset()         { *m = AuthenticateUserResponse{} }
func (m *AuthenticateUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserResponse) ProtoMessage()    {}
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef360b9da723b7a0, []int{1}
}

func (m *AuthenticateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserResponse.Unmarshal(m, b)
}
func (m *AuthenticateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserResponse.Merge(m, src)
}
func (m *AuthenticateUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserResponse.Size(m)
}
func (m *AuthenticateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserResponse proto.InternalMessageInfo

func (m *AuthenticateUserResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthenticateUserRequest)(nil), "user.AuthenticateUserRequest")
	proto.RegisterType((*AuthenticateUserResponse)(nil), "user.AuthenticateUserResponse")
}

func init() {
	proto.RegisterFile("github.com/meoconbatu/cmsgrpc/view/proto-files/user-service.proto", fileDescriptor_ef360b9da723b7a0)
}

var fileDescriptor_ef360b9da723b7a0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x40, 0xa9, 0xa8, 0x68, 0x8a, 0x20, 0xb9, 0xb8, 0x2c, 0x28, 0xb2, 0x7a, 0xf0, 0xd2, 0x04,
	0xea, 0x07, 0x48, 0x05, 0xf1, 0x26, 0x74, 0xc5, 0x8b, 0x27, 0xb3, 0xe9, 0xd8, 0x06, 0xcc, 0x4e,
	0x9c, 0x49, 0x5a, 0xfc, 0x7b, 0xc9, 0x2e, 0x0a, 0x2a, 0x8b, 0xf4, 0x38, 0xf3, 0xc8, 0xcb, 0x63,
	0xc4, 0x6c, 0xe9, 0xe2, 0x2a, 0x35, 0xca, 0xa2, 0xd7, 0x1e, 0xd0, 0x62, 0xdb, 0x98, 0x98, 0xb4,
	0xf5, 0xbc, 0xa4, 0x60, 0xf5, 0xda, 0xc1, 0x46, 0x07, 0xc2, 0x88, 0x93, 0x57, 0xf7, 0x06, 0xac,
	0x13, 0x03, 0x4d, 0x18, 0x68, 0xed, 0x2c, 0xa8, 0x0e, 0xc8, 0xdd, 0xbc, 0x2b, 0xef, 0xb7, 0x14,
	0x11, 0x04, 0x64, 0x17, 0x91, 0x3e, 0x7e, 0xea, 0xaa, 0xb9, 0x38, 0x99, 0xa5, 0xb8, 0x82, 0x36,
	0x3a, 0x6b, 0x22, 0x3c, 0x31, 0x50, 0x0d, 0xef, 0x09, 0x38, 0xca, 0x52, 0x1c, 0xe4, 0xbf, 0x1e,
	0x8c, 0x87, 0x62, 0x74, 0x3e, 0xba, 0x3a, 0xac, 0xbf, 0xe7, 0xcc, 0x82, 0x61, 0xde, 0x20, 0x2d,
	0x8a, 0x9d, 0x9e, 0x7d, 0xcd, 0xd5, 0x8d, 0x28, 0xfe, 0x2a, 0x39, 0x60, 0xcb, 0x20, 0x2f, 0xc4,
	0x1e, 0x10, 0x21, 0x75, 0xc2, 0xf1, 0xf4, 0x48, 0x2d, 0xd0, 0x1b, 0xd7, 0xaa, 0xbb, 0xbc, 0xac,
	0x7b, 0x36, 0x7d, 0x11, 0xe3, 0xfc, 0xe8, 0xb1, 0x0f, 0x95, 0x73, 0x71, 0xfc, 0xdb, 0x27, 0x4f,
	0x55, 0x4e, 0x51, 0x03, 0xe9, 0xe5, 0xd9, 0x10, 0xee, 0x33, 0x6e, 0x2f, 0x9f, 0xab, 0xff, 0x0f,
	0xd8, 0xec, 0x77, 0x27, 0xba, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x7b, 0x52, 0x0e, 0xb6,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error) {
	out := new(AuthenticateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/AuthenticateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) AuthenticateUser(ctx context.Context, req *AuthenticateUserRequest) (*AuthenticateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/AuthenticateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AuthenticateUser(ctx, req.(*AuthenticateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateUser",
			Handler:    _UserService_AuthenticateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/meoconbatu/cmsgrpc/view/proto-files/user-service.proto",
}
